#!/bin/sh
#
# report the file that's the same
#
if [ "$#" -lt "2" ]
then
   echo "  Usage: same <reference dir> <query dir1> <query dir2> ..."
   echo "    All files in the reference dir will be diffed against"
   echo "    the corresponding file in the query dir(s).  The ones"
   echo "    that don't differ will be printed."
   exit 0
fi

ANSWER=$1
shift 1
for j in $@
  do
    IS_SAME=0
    QUESTION=$j
    for i in $ANSWER/*.properties $ANSWER/*.js
      do
        if ! diff $i $QUESTION/cfg/ > /dev/null
        then IS_SAME=1
        fi
    done
    if [ $IS_SAME -eq 0 ]; then echo $QUESTION; fi
done
exit 0

